#!/usr/bin/env bash
# Emit Sources/AppInfo.swift from scripts/version.txt so app and release never
# drift. Run before every build:
#   bash scripts/emit-appinfo.sh
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION_FILE="$ROOT/scripts/version.txt"
VERSION="$(cat "$VERSION_FILE")"
BUILD="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo 0)"
if [[ "${DEV:-0}" == "1" ]]; then
  BUILD="dev-$BUILD"
  IS_DEV="true"
else
  IS_DEV="false"
fi
OUT="$ROOT/Sources/AppInfo.swift"
cat > "$OUT" <<SWIFT
// GENERATED by scripts/emit-appinfo.sh — do not edit by hand.
enum AppInfo {
    static let version = "$VERSION"
    static let build = "$BUILD"
    static let bundleID = "app.headroom.mac"
    static let isDevBuild = $IS_DEV
}
SWIFT
echo "Wrote $OUT (version $VERSION, build $BUILD, dev=$IS_DEV)"
